# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT 

# Uncomment the following line to enable the Sofle OLED Display
#CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=yS
# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Set sleep timeout to 10min (10*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_IDLE_TIMEOUT= 30000

#CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
#CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3


#The External power control behavior allows enabling or disabling the VCC power
#output to save power. Some of the LEDs will consume power even in OFF state. To
#preserve battery life in this scenario, some controller boards have support to
#disable the external power completely.
CONFIG_ZMK_EXT_POWER=y

#report battery levels from both sides of split keyboard (central/peripheral)
#see: https://zmk.dev/docs/config/battery#peripheral-battery-monitoring
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

